title: Project Page
options:
  navigation:
    status: all
    template: project

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          contentHeadline:
            type: headline
            label: "{{page.title}} page"
            numbered: false
          intro:
            label: Introduction text
            type: writer
            marks:
              - bold
              - italic
              - underline
              - link
              - email
              - clear
            nodes: false
          blocks:
            label: Additional text
            type: blocks
            fieldsets:
              - sectionblock
              - textblock
          cover:
            type: files
            label: Cover images
            uploads: media
            template: media         
            layout: cards
            multiple: true
            link: true
            size: small
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true 
          gallery:
            type: files
            label: Gallery
            uploads: media
            template: media         
            layout: cards
            multiple: true
            link: true
            size: small
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true 
  sidebar:
    width: 1/3
    sections:
      features:
        type: fields
        fields:   
          previewHeadline:
            type: headline
            label: "{{page.parent.title}} list preview" 
            numbered: false
          background:
            type: files
            label: Background image
            uploads:
              template: media 
            query: page.files
            layout: list
            size: small
            multiple: false
            image:
              back: "#000"
              icon: false
              ratio: 1/1
              cover: true
          filtersHeadline:
            type: headline
            label: Filter Settings
            numbered: false
          typeName:
            label: Filter by    
            type: text
            width: 1/2 
          types: 
            type: multiselect
            label: "Available filters (category: media)"
            layout: list  
            options:
              type: query
              query: site.mediaFilters.toStructure
              text: "{{ item.filter }}"
              value: "{{ item.filter }}"
          filterName:
            label: Filter by    
            type: text
            width: 1/2
          filters:
            type: multiselect
            label: "Available filters (category: process stage)"  
            layout: list
            options:
              type: query
              query: site.processFilters.toStructure
              text: "{{ item.filter }}"
              value: "{{ item.filter }}"