title: Project Page
options:
  navigation:
    status: all
    template: project

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          intro:
            label: Introduction text
            type: writer
            marks:
              - bold
              - italic
              - underline
              - link
              - email
              - clear
            nodes: false
          additionalTextInfo:
            label: false
            type: info
            text: 'The additional text below activates the "Read More" button.'
          textblocks:
            label: Additional text
            type: blocks
            pretty: true
            fieldsets:
              - textblock
          cover:
            type: files
            label: Cover images
            uploads: media-project
            template: media-project
            query: page.files
            layout: cards
            multiple: true
            link: true
            size: small
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          gallery:
            type: files
            label: Gallery
            uploads: media-project
            template: media-project     
            query: page.files    
            layout: cards
            multiple: true
            link: true
            size: small
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true 
  sidebar:
    width: 1/3
    sections:
      features:
        type: fields
        fields:   
          background:
            type: files
            label: Background image ({{page.parent.title}} list preview)
            uploads: media-project
            template: media-project 
            query: page.files
            layout: list
            size: small
            multiple: false
            image:
              back: "#000"
              icon: false
              ratio: 1/1
              cover: true
          selectFilters:
            label: Filter by
            type: multiselect
            layout: list
            search: false
            options:
              mediatype: Media type
              tool: Related tool