title: Site

tabs:
  page:
    label: Website pages
    icon: angle-right
    columns:
      main:
        width: 2/3
        sections:       
          allpages:
            label: Website pages
            type: pages
            image: false
            template:
              - home
              - projects
              - tools
              - platform      
              - about
          infos:
            label: false
            type: info
            text: "The pages above are linked to the site header navigation menu."
          oldTemplate:
            label: "Temporary area: old template [Platform]"
            type: pages
            image: false
            max: 1
            template:
              - themes    
      sidebar:
        width: 1/3
        sections:
          attachments:
            label: File attachments     
            type: files 
            batch: true
            template: pdf
            uploads: pdf
            query: site.files.template("pdf")
            multiple: true
            link: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          attachmentsInfo:
            label: false
            type: fields
            fields:
              attachmentsInfoText:
                label: false
                type: info
                text: "The above files can be linked as PDF attachments within the text. Upload here any PDFs you wish to use throughout the website."
          features:
            label: false
            type: fields
            fields:
              toggleLang:
                label: Languages
                type: toggle
                text: Want to display the languages switcher?
                default: false
              selectLanguages:
                label: Select languages
                type: multiselect
                options:
                  en: English
                  fr: Français
                  de: Deutsch
                multiple: true
                default: en
                info: "Select the languages you want to display on the site."
                when:
                  toggleLang: true
  contact:
    label: Contact
    icon: angle-right
    columns:
      main:
        width: 2/3
        sections:
          contact:
            type: fields
            fields:
              contactblocks:
                label: Contact items
                type: blocks
                pretty: true
                fieldsets:
                  - contactblock
      sidebar:
        width: 1/3
        sections:
          contactButtons:
            type: fields
            fields:
              contactNavLabel:
                label: Menu label
                type: text
              instagram:
                label: Instagram
                type: url
              instagramIcon:
                label: Instagram button style
                type: toggles
                width: 1/2
                options:
                  - value: text
                    text: Text [Instagram]
                  - value: icon
                    text: Abbreviation [IG]
                default: text
  filters:
    label: Filters collection
    icon: angle-right
    sections:
      filter:
        type: fields
        fields:
          filterinfos:
            label: false
            type: info
            text: |
              When updating an existing filter, always change the 'Filter Name' but keep the 'Key' the same. This way, your website will display the updated 'Filter Name' while keeping the filter properly assigned. If you change the 'Key' instead, every element on your site using that filter will lose it, and you'll need to reapply the filter manually. When creating a new filter, it's easiest to set the 'Key' and 'Filter Name' to match, with the option to change the 'Filter Name' in the future. Just keep in mind that keys must always be unique—no duplicates allowed.
          categoriesInfos:
            label: false
            type: info
            text: |
              Categories can be sorted and assigned a custom order. Other filters are automatically sorted alphabetically.
          categories:
            label: "Categories"
            width: 1/2
            type: structure
            fields:
              key:                
                type: text
                label: Key (unique–do not change)
              filter:
                type: text
                label: Filter Name
          mediatypes:
            label: "Media type"
            width: 1/2
            type: structure
            sortBy: filter asc
            fields:
              key: 
                type: text
                label: Key (unique–do not change)
              filter:
                type: text
                label: Filter Name
          itemtypes:
            label: "Event type"
            width: 1/2
            type: structure
            sortBy: filter asc
            fields:
              key:                
                type: text
                label: Key (unique–do not change)
              filter:
                type: text
                label: Filter Name   
          members:
            label: "Members"
            width: 1/2
            type: structure
            sortBy: filter asc
            fields:
              key: 
                type: text
                label: Key (unique–do not change)
              filter:
                type: text
                label: Filter Name
  seo:
    label: Website metadata
    icon: angle-right
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: Key (unique–do not change)words
                type: tags         
      image:
        width: 1/2
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: OG Image
                type: files
                template: image
                uploads: image
                layout: cards
                size: huge
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true



