title: Site

tabs:
  page:
    label: Website pages
    icon: angle-right
    columns:
      main:
        width: 2/3
        sections:       
          allpages:
            label: Website pages
            type: pages
            image: false
            template:
              - home
              - projects
              - tools
              - platform      
              - timeline
              - about
          infos:
            label: false
            type: info
            text: "The pages above are linked to the site header navigation menu."
          oldTemplate:
            label: "Temporary area: old template (Platform)"
            type: pages
            image: false
            max: 1
            template:
              - themes    
      sidebar:
        width: 1/3
        sections:
          attachments:
            label: File attachments     
            type: files 
            template: pdf
            uploads: pdf
            query: site.files.template("pdf")
            multiple: true
            link: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          attachmentsInfo:
            label: false
            type: fields
            fields:
              attachmentsInfoText:
                label: false
                type: info
                text: "The above files can be linked as PDF attachments within the text. Upload all the PDFs you'd like to use throughout the site here."
          features:
            label: false
            type: fields
            fields:
              toggleLang:
                label: Languages
                type: toggle
                text: Want to display the languages switcher?
                default: false
              # toggleLangInfo:
              #   label: false
              #   type: info
              #   text: "By activating the button above, the languages switcher will be displayed on the site footer."
              selectLanguages:
                label: Select languages
                type: multiselect
                options:
                  en: English
                  fr: Français
                  de: Deutsch
                multiple: true
                default: en
                info: "Select the languages you want to display on the site."
                when:
                  toggleLang: true
  # about:
  #   label: About
  #   icon: angle-right
  #   columns:
  #     main:
  #       width: 2/3
  #       sections:
  #         copy:
  #           type: fields
  #           fields:
  #             blocks:
  #               label: Text
  #               type: blocks
  #               fieldsets:
  #                 - sliderblock
  #                 - textblock
  #     sidebar:
  #       width: 1/3
  #       sections:
  #         aboutButtons:
  #           type: fields
  #           fields:
  #             aboutNavLabel:
  #               label: Menu label
  #               type: text
  contact:
    label: Contact
    icon: angle-right
    columns:
      main:
        width: 2/3
        sections:
          contact:
            type: fields
            fields:
              contactblocks:
                label: Contact items
                type: blocks
                fieldsets:
                  - contactblock
      sidebar:
        width: 1/3
        sections:
          contactButtons:
            type: fields
            fields:
              contactNavLabel:
                label: Menu label
                type: text
              instagram:
                label: Instagram
                type: url
              instagramIcon:
                label: Instagram button style
                type: toggles
                width: 1/2
                options:
                  - value: text
                    text: Text (Instagram)
                  - value: icon
                    text: Icon (IG)
                default: text
  filters:
    label: Filters collection
    icon: angle-right
    sections:
      filter:
        type: fields
        fields:
          mediaFilters:
            label: "Category: media"
            type: structure
            fields:
              filter:
                type: text
                label: Filter
          processFilters:
            label: "Category: process stage"
            type: structure
            fields:
              filter:
                type: text
                label: Filter
          platformFilters:
            label: "Category: events"
            type: structure
            fields:
              filter:
                type: text
                label: Filter
          platformFilters:
            label: "Category: platform"
            type: structure
            fields:
              filter:
                type: text
                label: Filter      
          membersFilters:
            label: "Category: members"
            type: structure
            fields:
              filter:
                type: text
                label: Filter
  seo:
    label: Website metadata
    icon: angle-right
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/2
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: OG Image
                type: files
                template: image
                uploads: image
                layout: cards
                size: huge
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true



